<?php
namespace lib\db\transactionitems;
trait auto_insert
{
/**
* the transaction items array
*
* hint of transactionitems id
*
* id                              =  id unit destination (to) . id unit origin (from) . [transaction type code] . [operation code | by sort]
* transaction type code           =
* {
* 		real		: 1,
* 		gift		: 2,
* 		prize		: 3,
* 		transfer	: 4,
* }
*
* operation code                  =
* {
* 		charge		: 01,
* 		change		: 02,
* 		answer		: 03,
* 		remove		: 04,
* 		...
* }
*
*
* @var        array
*/
private static $AUTO_INSERT       =
[
// for test
'charge:real'                     => ['id' => 1010, 'unit_id' => 1, 'type' => 'real', 	'caller' => 'charge:real', 'title' => 'charge for test', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
// repair caller
'repair:real:tejarak'             => ['id' => null, 'unit_id' => 1, 'type' => 'real', 	'caller' => 'repair:real:tejarak', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:real:toman'               => ['id' => null, 'unit_id' => 2, 'type' => 'real', 	'caller' => 'repair:real:toman', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:real:dollar'              => ['id' => null, 'unit_id' => 3, 'type' => 'real', 	'caller' => 'repair:real:dollar', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'repair:gift:tejarak'             => ['id' => null, 'unit_id' => 1, 'type' => 'gift', 	'caller' => 'repair:gift:tejarak', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:gift:toman'               => ['id' => null, 'unit_id' => 2, 'type' => 'gift', 	'caller' => 'repair:gift:toman', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:gift:dollar'              => ['id' => null, 'unit_id' => 3, 'type' => 'gift', 	'caller' => 'repair:gift:dollar', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'repair:prize:tejarak'            => ['id' => null, 'unit_id' => 1, 'type' => 'prize', 	'caller' => 'repair:prize:tejarak', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:prize:toman'              => ['id' => null, 'unit_id' => 2, 'type' => 'prize', 	'caller' => 'repair:prize:toman', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:prize:dollar'             => ['id' => null, 'unit_id' => 3, 'type' => 'prize', 	'caller' => 'repair:prize:dollar', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'repair:transfer:tejarak'         => ['id' => null, 'unit_id' => 1, 'type' => 'transfer', 	'caller' => 'repair:transfer:tejarak', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:transfer:toman'           => ['id' => null, 'unit_id' => 2, 'type' => 'transfer', 	'caller' => 'repair:transfer:toman', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'repair:transfer:dollar'          => ['id' => null, 'unit_id' => 3, 'type' => 'transfer', 	'caller' => 'repair:transfer:dollar', 'title' => 'repair transaction', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],


'gift:charge:toman'               => ['id' => null, 'unit_id' => 2, 'type' => 'gift', 	'caller' => 'gift:charge:toman', 'title' => 'gift charge toman', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'real:answer:poll:tejarak'        => ['id' => 1013, 'unit_id' => 1, 'type' => 'real', 	'caller' => 'real:answer:poll:tejarak', 'title' => 'answer to public poll', 'minus' => null,'plus' => '2','autoverify' => 'yes','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:answer:custom:poll:tejarak' => ['id' => 1017, 'unit_id' => 1, 'type' => 'real', 	'caller' => 'real:answer:custom:poll:tejarak', 'title' => 'answer to tejarak custom poll', 'minus' => null,'plus' => '2','autoverify' => 'yes','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'remove:answer:poll:tejarak'      => ['id' => 1016, 'unit_id' => 1, 'type' => 'real', 	'caller' => 'remove:answer:poll:tejarak', 'title' => 'remove answer of public poll', 'minus' => null,'plus' => null,'autoverify' => 'yes','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'gift:signup'                     => ['id' => 1024, 'unit_id' => 1, 'type' => 'gift', 	'caller' => 'gift:signup', 'title' => 'charge on signup', 'minus' => null,'plus' => '1000','autoverify' => 'no','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'gift:profile:complete'           => ['id' => 1025, 'unit_id' => 1, 'type' => 'gift', 	'caller' => 'gift:profile:complete', 'title' => 'charge on complete profile', 'minus' => null,'plus' => '1000','autoverify' => 'yes','forcechange' => 'yes','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'real:charge:toman'               => ['id' => 2011, 'unit_id' => 2, 'type' => 'real', 	'caller' => 'real:charge:toman', 'title' => 'real charge toman', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:answer:poll:toman'          => ['id' => 2013, 'unit_id' => 2, 'type' => 'real', 	'caller' => 'real:answer:poll:toman', 'title' => 'answer to public poll', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'remove:answer:poll:toman'        => ['id' => 2016, 'unit_id' => 2, 'type' => 'real', 	'caller' => 'remove:answer:poll:toman', 'title' => 'remove answer of public poll', 'minus' => null,'plus' => null,'autoverify' => 'yes','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'change:tejarak:toman'            => ['id' => 2112, 'unit_id' => 2, 'type' => 'real', 	'caller' => 'change:tejarak:toman', 'title' => 'change tejarak to toman', 'minus' => null,'plus' => null,'autoverify' => 'yes','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'change:dollar:toman'             => ['id' => 2312, 'unit_id' => 2, 'type' => 'real', 	'caller' => 'change:dollar:toman', 'title' => 'dollar to toman', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'real:charge:dollar'              => ['id' => 3011, 'unit_id' => 3, 'type' => 'real', 	'caller' => 'real:charge:dollar', 'title' => 'real charge $', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:answer:poll:dollar'         => ['id' => 3013, 'unit_id' => 3, 'type' => 'real', 	'caller' => 'real:answer:poll:dollar', 'title' => 'answer to public poll', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'remove:answer:poll:dollar'       => ['id' => 3016, 'unit_id' => 3, 'type' => 'real', 	'caller' => 'remove:answer:poll:dollar', 'title' => 'remove answer of public poll', 'minus' => null,'plus' => null,'autoverify' => 'yes','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'change:tejarak:dollar'           => ['id' => 3112, 'unit_id' => 3, 'type' => 'real', 	'caller' => 'change:tejarak:dollar', 'title' => 'change tejarak to $', 'minus' => null,'plus' => null,'autoverify' => 'yes','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],
'change:toman:dollar'             => ['id' => 3212, 'unit_id' => 3, 'type' => 'real', 	'caller' => 'change:toman:dollar', 'title' => 'toman to dollar', 'minus' => null,'plus' => null,'autoverify' => 'no','forcechange' => 'no','desc' => null,'meta' => null,'status' => 'enable','count' => 0, 'enddate' => null, 'date_modified' => null,],

'real:change:minus:tejarak'       => ['id' => null, 'unit_id' => 1, 'type' => 'real',		'caller' => 'real:change:minus:tejarak', 'title' => 'minus tejarak real for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:change:plus:tejarak'        => ['id' => null, 'unit_id' => 1, 'type' => 'real',		'caller' => 'real:change:plus:tejarak', 'title' => 'plus tejarak real for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:change:minus:toman'         => ['id' => null, 'unit_id' => 2, 'type' => 'real',		'caller' => 'real:change:minus:toman', 'title' => 'minus toman real for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:change:plus:toman'          => ['id' => null, 'unit_id' => 2, 'type' => 'real',		'caller' => 'real:change:plus:toman', 'title' => 'plus toman real for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:change:minus:dollar'        => ['id' => null, 'unit_id' => 3, 'type' => 'real',		'caller' => 'real:change:minus:dollar', 'title' => 'minus dollar real for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'real:change:plus:dollar'         => ['id' => null, 'unit_id' => 3, 'type' => 'real',		'caller' => 'real:change:plus:dollar', 'title' => 'plus dollar real for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'gift:change:minus:tejarak'       => ['id' => null, 'unit_id' => 1, 'type' => 'gift',		'caller' => 'gift:change:minus:tejarak', 'title' => 'minus tejarak gift for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'gift:change:plus:tejarak'        => ['id' => null, 'unit_id' => 1, 'type' => 'gift',		'caller' => 'gift:change:plus:tejarak', 'title' => 'plus tejarak gift for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'gift:change:minus:toman'         => ['id' => null, 'unit_id' => 2, 'type' => 'gift',		'caller' => 'gift:change:minus:toman', 'title' => 'minus toman gift for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'gift:change:plus:toman'          => ['id' => null, 'unit_id' => 2, 'type' => 'gift',		'caller' => 'gift:change:plus:toman', 'title' => 'plus toman gift for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'gift:change:minus:dollar'        => ['id' => null, 'unit_id' => 3, 'type' => 'gift',		'caller' => 'gift:change:minus:dollar', 'title' => 'minus dollar gift for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'gift:change:plus:dollar'         => ['id' => null, 'unit_id' => 3, 'type' => 'gift',		'caller' => 'gift:change:plus:dollar', 'title' => 'plus dollar gift for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'prize:change:plus:tejarak'       => ['id' => null, 'unit_id' => 1, 'type' => 'prize',	'caller' => 'prize:change:plus:tejarak', 'title' => 'plus tejarak prize for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'prize:change:minus:tejarak'      => ['id' => null, 'unit_id' => 1, 'type' => 'prize',	'caller' => 'prize:change:minus:tejarak', 'title' => 'minus tejarak prize for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'prize:change:minus:toman'        => ['id' => null, 'unit_id' => 2, 'type' => 'prize',	'caller' => 'prize:change:minus:toman', 'title' => 'minus toman prize for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'prize:change:plus:toman'         => ['id' => null, 'unit_id' => 2, 'type' => 'prize',	'caller' => 'prize:change:plus:toman', 'title' => 'plus toman prize for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'prize:change:minus:dollar'       => ['id' => null, 'unit_id' => 3, 'type' => 'prize',	'caller' => 'prize:change:minus:dollar', 'title' => 'minus dollar prize for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'prize:change:plus:dollar'        => ['id' => null, 'unit_id' => 3, 'type' => 'prize',	'caller' => 'prize:change:plus:dollar', 'title' => 'plus dollar prize for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'transfer:change:minus:tejarak'   => ['id' => null, 'unit_id' => 1, 'type' => 'transfer',	'caller' => 'transfer:change:minus:tejarak', 'title' => 'minus tejarak transfer for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'transfer:change:plus:tejarak'    => ['id' => null, 'unit_id' => 1, 'type' => 'transfer',	'caller' => 'transfer:change:plus:tejarak', 'title' => 'plus tejarak transfer for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'transfer:change:minus:toman'     => ['id' => null, 'unit_id' => 2, 'type' => 'transfer',	'caller' => 'transfer:change:minus:toman', 'title' => 'minus toman transfer for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'transfer:change:plus:toman'      => ['id' => null, 'unit_id' => 2, 'type' => 'transfer',	'caller' => 'transfer:change:plus:toman', 'title' => 'plus toman transfer for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'transfer:change:minus:dollar'    => ['id' => null, 'unit_id' => 3, 'type' => 'transfer',	'caller' => 'transfer:change:minus:dollar', 'title' => 'minus dollar transfer for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'transfer:change:plus:dollar'     => ['id' => null, 'unit_id' => 3, 'type' => 'transfer',	'caller' => 'transfer:change:plus:dollar', 'title' => 'plus dollar transfer for change', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'no', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'add:poll:minus:real:tejarak'     => ['id' => null, 'unit_id' => 1, 'type' => 'real',		'caller' => 'add:poll:minus:real:tejarak', 'title' => 'minus real money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:gift:tejarak'     => ['id' => null, 'unit_id' => 1, 'type' => 'gift',		'caller' => 'add:poll:minus:gift:tejarak', 'title' => 'minus gift money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:prize:tejarak'    => ['id' => null, 'unit_id' => 1, 'type' => 'prize',	'caller' => 'add:poll:minus:prize:tejarak', 'title' => 'minus prize money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:transfer:tejarak' => ['id' => null, 'unit_id' => 1, 'type' => 'transfer',	'caller' => 'add:poll:minus:transfer:tejarak', 'title' => 'minus transfer money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'add:poll:minus:real:toman'       => ['id' => null, 'unit_id' => 2, 'type' => 'real',		'caller' => 'add:poll:minus:real:toman', 'title' => 'minus real money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:gift:toman'       => ['id' => null, 'unit_id' => 2, 'type' => 'gift',		'caller' => 'add:poll:minus:gift:toman', 'title' => 'minus gift money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:prize:toman'      => ['id' => null, 'unit_id' => 2, 'type' => 'prize',	'caller' => 'add:poll:minus:prize:toman', 'title' => 'minus prize money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:transfer:toman'   => ['id' => null, 'unit_id' => 2, 'type' => 'transfer',	'caller' => 'add:poll:minus:transfer:toman', 'title' => 'minus transfer money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'add:poll:minus:real:dollar'      => ['id' => null, 'unit_id' => 3, 'type' => 'real',		'caller' => 'add:poll:minus:real:dollar', 'title' => 'minus real money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:gift:dollar'      => ['id' => null, 'unit_id' => 3, 'type' => 'gift',		'caller' => 'add:poll:minus:gift:dollar', 'title' => 'minus gift money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:prize:dollar'     => ['id' => null, 'unit_id' => 3, 'type' => 'prize',	'caller' => 'add:poll:minus:prize:dollar', 'title' => 'minus prize money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'add:poll:minus:transfer:dollar'  => ['id' => null, 'unit_id' => 3, 'type' => 'transfer',	'caller' => 'add:poll:minus:transfer:dollar', 'title' => 'minus transfer money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'stop:poll:back:real:tejarak'     => ['id' => null, 'unit_id' => 1, 'type' => 'real',		'caller' => 'stop:poll:back:real:tejarak', 'title' => 'minus real money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:gift:tejarak'     => ['id' => null, 'unit_id' => 1, 'type' => 'gift',		'caller' => 'stop:poll:back:gift:tejarak', 'title' => 'minus gift money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:prize:tejarak'    => ['id' => null, 'unit_id' => 1, 'type' => 'prize',	'caller' => 'stop:poll:back:prize:tejarak', 'title' => 'minus prize money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:transfer:tejarak' => ['id' => null, 'unit_id' => 1, 'type' => 'transfer',	'caller' => 'stop:poll:back:transfer:tejarak', 'title' => 'minus transfer money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'stop:poll:back:real:toman'       => ['id' => null, 'unit_id' => 2, 'type' => 'real',		'caller' => 'stop:poll:back:real:toman', 'title' => 'minus real money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:gift:toman'       => ['id' => null, 'unit_id' => 2, 'type' => 'gift',		'caller' => 'stop:poll:back:gift:toman', 'title' => 'minus gift money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:prize:toman'      => ['id' => null, 'unit_id' => 2, 'type' => 'prize',	'caller' => 'stop:poll:back:prize:toman', 'title' => 'minus prize money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:transfer:toman'   => ['id' => null, 'unit_id' => 2, 'type' => 'transfer',	'caller' => 'stop:poll:back:transfer:toman', 'title' => 'minus transfer money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],

'stop:poll:back:real:dollar'      => ['id' => null, 'unit_id' => 3, 'type' => 'real',		'caller' => 'stop:poll:back:real:dollar', 'title' => 'minus real money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:gift:dollar'      => ['id' => null, 'unit_id' => 3, 'type' => 'gift',		'caller' => 'stop:poll:back:gift:dollar', 'title' => 'minus gift money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:prize:dollar'     => ['id' => null, 'unit_id' => 3, 'type' => 'prize',	'caller' => 'stop:poll:back:prize:dollar', 'title' => 'minus prize money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],
'stop:poll:back:transfer:dollar'  => ['id' => null, 'unit_id' => 3, 'type' => 'transfer',	'caller' => 'stop:poll:back:transfer:dollar', 'title' => 'minus transfer money for add poll', 'minus' => null, 'plus' => null, 'autoverify' => 'yes', 'forcechange' => 'yes', 'desc' => null, 'meta' => null, 'status' => 'enable', 'count' => 0, 'enddate' => null, 'date_modified' => null,],


];
}
?>