ALTER TABLE `users` CHANGE `user_mobile` `mobile` varchar(15) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_email` `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_pass` `password` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_displayname` `displayname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_meta` `meta` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE `users` CHANGE `user_status` `status` enum('active','awaiting','deactive','removed','filter','unreachable') DEFAULT 'awaiting';
ALTER TABLE `users` CHANGE `user_parent` `parent` int(10) UNSIGNED DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_permission` `permission` varchar(1000) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_type` `type` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_createdate` `datecreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` CHANGE `date_modified` `datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `users` CHANGE `user_username` `username` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_group` `group` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_file_id` `fileid` int(20) UNSIGNED DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_chat_id` `chatid` int(20) UNSIGNED DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_pin` `pin` smallint(4) UNSIGNED DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_ref` `ref` int(10) UNSIGNED DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_creator` `creator` int(10) UNSIGNED DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_two_step` `twostep` bit(1) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_google_mail` `googlemail` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_facebook_mail` `facebookmail` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_twitter_mail` `twittermail` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_dont_will_set_mobile` `dontwillsetmobile` varchar(50) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_file_url` `fileurl` varchar(2000) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_notification` `notification` text;
ALTER TABLE `users` CHANGE `user_setup` `setup` bit(1) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_name` `name` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_family` `lastname` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_father` `father` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_birthday` `birthday` datetime DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_code` `shcode` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_nationalcode` `nationalcode` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_from` `shfrom` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_nationality` `nationality` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_brithplace` `brithplace` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_region` `region` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_pasportcode` `pasportcode` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_marital` `marital` enum('single','marride') DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_gender` `gender` enum('male','female') DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_childcount` `childcount` smallint(2) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_education` `education` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_insurancetype` `insurancetype` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_insurancecode` `insurancecode` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_dependantscount` `dependantscount` smallint(4) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_postion` `postion` varchar(100) DEFAULT NULL;
ALTER TABLE `users` CHANGE `user_language` `language` char(2) DEFAULT NULL;
