CREATE TABLE teams (
`id`					       int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`title`					     varchar(500) NOT NULL,
`site`					     varchar(1000) NULL DEFAULT NULL,
`boss`					     int(10) UNSIGNED NULL DEFAULT NULL,
`creator`					   int(10) UNSIGNED NOT NULL,
`technical`					 int(10) UNSIGNED NULL DEFAULT NULL,
`brand`					     varchar(100) NULL DEFAULT NULL,
`register_code`			 int(10) UNSIGNED NULL DEFAULT NULL,
`economical_code`		 int(10) UNSIGNED NULL DEFAULT NULL,
`telegram_id`				 varchar(50) NULL DEFAULT NULL,
`file_id`					   int(20) UNSIGNED NULL DEFAULT NULL,
`logo`					     int(20) UNSIGNED NULL DEFAULT NULL,
`alias`					     varchar(1000) NULL DEFAULT NULL,
`plan`					     varchar(50) NULL DEFAULT NULL,
`until`					     datetime NULL DEFAULT NULL,
`status`					   enum('enable','disable','expire') NOT NULL DEFAULT 'enable',
`createdate`				 datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified`			 timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc`					     text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
`meta`					     mediumtext  CHARACTER SET utf8mb4 NULL DEFAULT NULL,
PRIMARY KEY (`id`),
CONSTRAINT `teams_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `teams_boss` FOREIGN KEY (`boss`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `teams_technical` FOREIGN KEY (`technical`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE branchs (
`id`			          int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`team_id`			  int(10) UNSIGNED NOT NULL,
`title`			        varchar(500) NOT NULL,
`site`			        varchar(1000) NULL DEFAULT NULL,
`boss`			        int(10) UNSIGNED NULL DEFAULT NULL,
`creator`			      int(10) UNSIGNED NULL DEFAULT NULL,
`technical`			    int(10) UNSIGNED NULL DEFAULT NULL,
`address`			      text NULL DEFAULT NULL,
`code`			        int(10) UNSIGNED NULL DEFAULT NULL,
`telegram_id`			  varchar(50) NULL DEFAULT NULL,
`phone_1`			      varchar(50) NULL DEFAULT NULL,
`phone_2`			      varchar(50) NULL DEFAULT NULL,
`phone_3`			      varchar(50) NULL DEFAULT NULL,
`fax`			          varchar(50) NULL DEFAULT NULL,
`email`			        varchar(50) NULL DEFAULT NULL,
`post_code`			    varchar(50) NULL DEFAULT NULL,
`full_time`			    bit(1) NULL DEFAULT NULL,
`remote`			      bit(1) NULL DEFAULT NULL,
`is_default`			  bit(1) NULL DEFAULT NULL,
`status`			      enum('enable','disable','expire') DEFAULT 'enable',
`createdate`			  datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified`			timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc`			        text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
`meta`			        mediumtext  CHARACTER SET utf8mb4 NULL DEFAULT NULL,
PRIMARY KEY (`id`),
CONSTRAINT `branchs_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `branchs_boss` FOREIGN KEY (`boss`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `branchs_technical` FOREIGN KEY (`technical`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `branchs_team_id` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE userteams (
`id`           			int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`team_id`   			int(10) UNSIGNED NOT NULL,
`user_id`      			int(10) UNSIGNED NOT NULL,
`postion`      			varchar(255) NULL DEFAULT NULL,
`code`         			int(10) UNSIGNED NULL DEFAULT NULL,
`telegram_id`  			varchar(50) NULL DEFAULT NULL,
`full_time`    			bit(1) NULL DEFAULT NULL,
`remote`       			bit(1) NULL DEFAULT NULL,
`is_default`   			bit(1) NULL DEFAULT NULL,
`date_enter`   			datetime NULL DEFAULT CURRENT_TIMESTAMP,
`date_exit`   			datetime NULL DEFAULT NULL,
`status`       			enum('enable','disable','expire') DEFAULT 'enable',
`createdate`   			datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified` 		timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc`          		text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
`meta`          		mediumtext  CHARACTER SET utf8mb4 NULL DEFAULT NULL,
PRIMARY KEY (`id`),
CONSTRAINT `userteams_team_id` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON UPDATE CASCADE,
CONSTRAINT `userteams_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE userbranchs (
`id`           		int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`team_id`   		int(10) UNSIGNED NOT NULL,
`branch_id`   		int(10) UNSIGNED NOT NULL,
`user_id`     		int(10) UNSIGNED NOT NULL,
`postion`      		varchar(255) NULL DEFAULT NULL,
`code`         		int(10) UNSIGNED NULL DEFAULT NULL,
`telegram_id`  		varchar(50) NULL DEFAULT NULL,
`full_time`    		bit(1) NULL DEFAULT NULL,
`remote`       		bit(1) NULL DEFAULT NULL,
`is_default`   		bit(1) NULL DEFAULT NULL,
`date_enter`   		datetime NULL DEFAULT CURRENT_TIMESTAMP,
`date_exit`   		datetime NULL DEFAULT NULL,
`status`       		enum('enable','disable','expire') DEFAULT 'enable',
`createdate`   		datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified` 	timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc`          	text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
`meta`          	mediumtext  CHARACTER SET utf8mb4 NULL DEFAULT NULL,
PRIMARY KEY (`id`),
CONSTRAINT `userbranch_team_id` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON UPDATE CASCADE,
CONSTRAINT `userbranch_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branchs` (`id`) ON UPDATE CASCADE,
CONSTRAINT `userbranch_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE getwaies (
`id`           		int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`team_id`   		int(10) UNSIGNED NOT NULL,
`branch_id` 	 		int(10) UNSIGNED NOT NULL,
`user_id`      		int(10) UNSIGNED NOT NULL,
`title` 	     		varchar(255) NULL DEFAULT NULL,
`cat`		  	  		varchar(255) NULL DEFAULT NULL,
`code`         		int(10) UNSIGNED NULL DEFAULT NULL,
`ip`	         		int(10) UNSIGNED NULL DEFAULT NULL,
`agent_id`  	 		int(10) UNSIGNED NULL DEFAULT NULL,
`status`       		enum('enable','disable','expire') DEFAULT 'enable',
`createdate`   		datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified` 	timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc`          	text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
`meta`          mediumtext  CHARACTER SET utf8mb4 NULL DEFAULT NULL,
PRIMARY KEY (`id`),
CONSTRAINT `getway_team_id` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON UPDATE CASCADE,
CONSTRAINT `getway_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branchs` (`id`) ON UPDATE CASCADE,
CONSTRAINT `getway_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `hours` (
`id`							      int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`user_id`							  int(10) UNSIGNED NOT NULL,
`team_id`						int(10) UNSIGNED NOT NULL,
`userteam_id`				int(10) UNSIGNED NOT NULL,
`userbranch_id`					int(10) UNSIGNED NOT NULL,
`start_getway_id`				int(10) UNSIGNED NOT NULL,
`end_getway_id`					int(10) UNSIGNED NULL DEFAULT NULL,
`start_userbranch_id`		int(10) UNSIGNED NOT NULL,
`end_userbranch_id`			int(10) UNSIGNED NULL DEFAULT NULL,
`date`							    date NOT NULL,
`year`							    int(4) UNSIGNED NOT NULL,
`month`							    int(2) UNSIGNED NOT NULL,
`day`							      int(2) UNSIGNED NOT NULL,
`shamsi_date`						date NOT NULL,
`shamsi_year`						int(4) UNSIGNED NOT NULL,
`shamsi_month`					int(2) UNSIGNED NOT NULL,
`shamsi_day`						int(2) UNSIGNED NOT NULL,
`start`							    time NOT NULL,
`end`							      time DEFAULT NULL,
`diff`							    int(10) UNSIGNED DEFAULT NULL,
`minus`							    int(10) UNSIGNED DEFAULT NULL,
`plus`							    int(10) UNSIGNED DEFAULT NULL,
`type`							    enum('nothing','base','wplus','wminus','all') DEFAULT 'all',
`accepted`							int(10) UNSIGNED DEFAULT NULL,
`createdate`						datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified`					timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`status`						enum('active','awaiting','deactive','removed','filter') DEFAULT 'awaiting',
PRIMARY KEY (`id`),
CONSTRAINT `hours_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `hourlogs` (
`id`                    int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`team_id`		        int(10) UNSIGNED NOT NULL,
`user_id`               int(10) UNSIGNED NOT NULL,
`userteam_id`        int(10) UNSIGNED NOT NULL,
`userbranch_id`         int(10) UNSIGNED NOT NULL,
`date`     							date NOT NULL,
`shamsi_date`    				date NOT NULL,
`time`    							time NOT NULL,
`minus`    							int(10) UNSIGNED DEFAULT NULL,
`plus`     							int(10) UNSIGNED DEFAULT NULL,
`type`     							enum('enter','exit') DEFAULT NULL,
`createdate`   					datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified` 				timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
